### ISSUE TITLE
Customize document header

### ISSUE THREAD

**Issue by mu373** [mu373/documentation#43]
## Overview
Allow the documents to have "headers" which shows additional informations just below the title.

## Implementations
- Swizzle [DocItem](https://github.com/facebook/docusaurus/tree/31b279fea6f19e520c0aea8b91dcf65c77f16560/packages/docusaurus-theme-classic/src/theme/DocItem)/[Content](https://github.com/facebook/docusaurus/tree/31b279fea6f19e520c0aea8b91dcf65c77f16560/packages/docusaurus-theme-classic/src/theme/DocItem/Content) from the theme
- Accept following informations in frontmatter:
```yml
title: Title Shown in <title>tag
custom_title: Custom title shown in the article #This precedes the "title" tag or the H1 tag in Markdown
sidebar_label: Label shown in the sidebar and breadcrumbs
header: #Additional informations to show in header
  foo: 123
  bar: 456
```
